embeddings {
  tensor_name: "embedding:0"
  metadata_path: "E:/python/tensorflow-class/projector/projector/metadata.tsv"
  sprite {
    image_path: "E:/python/tensorflow-class/projector/projector/mnist_10k_sprite.png"
    single_image_dim: 28
    single_image_dim: 28
  }
}
